### ISSUE TITLE
Properties such as -Dsonar.host seems to be ignored

### ISSUE THREAD

**Issue by amottier** [jerkar/sonarqube-plugin#2]
I'm running the following command: `./jeka/output/distrib/jeka java#pack -java#test.fork=true @dev.jeka:jacoco-plugin:1.0.0.RC3 jacoco# -jacoco#classDirExcludes=META-INF/**/* @dev.jeka:sonarqube-plugin:1.0.0.RC1 sonarqube#run -Dsonar.host=https://invalidhostname.ow2.org -Dsonar.login=abc123 -LB` and despite the SonarQube server URL being invalid I got in the log only the following message:
```
Launch Sonar analysis wih sonar-scanner-cli-4.6.2.2472.jar
```

I'm wondering if there is anything I can do to get some logging information from Sonar plugin or maybe directly from Sonar Scanner?

Thanks.

**Comment by djeang** [comment]
You can try -LV (Log Verbose) option.

**Comment by djeang** [comment]
1.0.0.RC2 will fix it. Build will fails when sonar process fails.
I think the default output can be improved as well : Display Sonar output on failure, do not show when it's ok.
Other feedback welcome.

**Comment by djeang** [comment]
One remark : according your command line, the build should fail at 'pack', cause it will try to recreate the jeka.jar that it is running. I can suggest you to run a `java#test` instead of `jeka#pack`, it should be enough to run jacoco+sonar on.

**Comment by amottier** [comment]
Thanks a lot, RC2 now failed if server URL is not correct and `-LV` help me identify that Sonar Scanner CLI was not taking into account my parameter. The issue is in fact related to the parameter name, it should be `-Dsonar.host.url` and no `-Dsonar.host`.
